<?php
/**
 * Staff ordering form — reachable only via a personal, one-time-use link
 * (?key=<token>, generated by scripts/generate-staff-invites.php). Renders
 * the same form as order.php (attendance/lunch-box UI reused as-is) with
 * $staffMode = true, which order.php uses to lock identity, make Campus/Life
 * Group optional (falls back to "Crosspoint"/"Staff" server-side if left
 * blank — see staff-checkout.php), and skip the public ordering window.
 * Submission goes to staff-checkout.php, not create-checkout.php.
 */
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/includes/db.php';
require_once __DIR__ . '/includes/helpers.php';
require_once __DIR__ . '/includes/layout.php';
require_once __DIR__ . '/includes/staff_tokens.php';

$_GET['lang'] = 'en'; // staff pages are English-only, no language selector

$key = trim((string) ($_GET['key'] ?? ''));
$staffPerson = staff_token_lookup($pdo, $key);

if ($staffPerson === null || $staffPerson['used_at'] !== null) {
    layout_head('Staff Order');
    ?>
    <div class="card border-red-300 bg-red-50 text-red-800">
      <h1 class="text-xl font-bold mb-2">This link is no longer valid</h1>
      <p>This ordering link is invalid or has already been used. Each staff link can only be
        used once. If you believe this is a mistake, contact the church office at
        <a href="mailto:cd@crosspointchurchsv.org" class="underline">cd@crosspointchurchsv.org</a>.</p>
    </div>
    <?php
    layout_footer();
    exit;
}

$staffMode  = true;
$staffToken = $key;
$old = [
    'first_name' => $staffPerson['first_name'],
    'last_name'  => $staffPerson['last_name'],
    'email'      => $staffPerson['email'],
    'campus'     => '',
    'lift_group' => '',
];

require __DIR__ . '/order.php';
